In [1]:
#Import Libraries
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Project Paths
# Project directories
BASE_DIR = Path("../../")
RAW_DATA = BASE_DIR / "data/raw"
CLEAN_DATA = BASE_DIR / "data/cleaned"

print("Raw data folder:", RAW_DATA)

Raw data folder: ..\..\data\raw

In [16]:
#List available datasets
list(RAW_DATA.glob("*.csv"))

[WindowsPath('../../data/raw/Depository Corporation Survey.csv'),
 WindowsPath('../../data/raw/Foreign Trade Summary.csv'),
 WindowsPath('../../data/raw/gdp_annual.csv'),
 WindowsPath('../../data/raw/inflation.csv'),
 WindowsPath('../../data/raw/Monthly Exchange rate (period average).csv'),
 WindowsPath('../../data/raw/Principal Exports Volume, Value and Unit Prices.csv'),
 WindowsPath('../../data/raw/Value of Exports to Selected African Countries.csv'),
 WindowsPath('../../data/raw/Value of Exports to Selected Rest of World Countries.csv'),
 WindowsPath('../../data/raw/Value of Selected Domestic Exports.csv')]

In [ ]:
#Load my datasets
inflation = pd.read_csv(RAW_DATA / "inflation.csv")
gdp = pd.read_csv(RAW_DATA / "gdp_annual.csv")
monetary = pd.read_csv(RAW_DATA / "depository_corporation_survey.csv")
trade_summary = pd.read_csv(RAW_DATA / "foreign_trade_summary.csv")
principal_exports = pd.read_csv(RAW_DATA / "principal_exports_volume_value_unit_prices.csv")
value_domestic_exports = pd.read_csv(RAW_DATA / "value_select_domestic_exports.csv")
value_exports_african = pd.read_csv(RAW_DATA / "value_exports_selected_african_countries.csv")
value_exports_restofworld = pd.read_csv(RAW_DATA / "value_exports_restofworld.csv")
exchange_rate = pd.read_csv(RAW_DATA / "monthly_exchange_rate_period_average.csv")

In [22]:
#helper function
def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("-", "_")
    )
    return df

In [23]:
#apply helper function
inflation = clean_columns(inflation)
gdp = clean_columns(gdp)
monetary = clean_columns(monetary)
trade_summary = clean_columns(trade_summary)
principal_exports = clean_columns(principal_exports)
value_domestic_exports = clean_columns(value_domestic_exports)
value_exports_african = clean_columns(value_exports_african)
value_exports_restofworld = clean_columns(value_exports_restofworld)
exchange_rate = clean_columns(exchange_rate)

In [24]:
#date column for time series analysis #inflation
inflation["date"] = pd.to_datetime(
    inflation["year"].astype(str) + "-" + inflation["month"].astype(str)
)

inflation = inflation.sort_values("date")

inflation.head()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_10216\3013194280.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  inflation["date"] = pd.to_datetime(

     year     month  annual_average_inflation  12_month_inflation       date
253  2005   January                     12.27               14.87 2005-01-01
252  2005  February                     12.60               13.94 2005-02-01
251  2005     March                     13.07               14.15 2005-03-01
250  2005     April                     13.76               16.02 2005-04-01
249  2005       May                     14.61               14.78 2005-05-01

In [ ]:
#Handling Missing values
#drop missing rows #using a dictionary
datasets = {
    "inflation": inflation,
    "gdp": gdp,
    "monetary": monetary,
    "trade_summary": trade_summary,
    "principal_exports": principal_exports,
    "value_domestic_exports": value_domestic_exports,
    "value_exports_african": value_exports_african,
    "value_exports_restofworld": value_exports_restofworld,
    "exchange_rate": exchange_rate
}

for name, df in datasets.items():
    datasets[name] = df.dropna()

,unnamed:_0,kenya_shilling_monthly_average_exchange_rates\1,unnamed:_2,unnamed:_3,unnamed:_4,unnamed:_5,unnamed:_6,unnamed:_7,unnamed:_8,unnamed:_9,...,unnamed:_21,unnamed:_22,unnamed:_23,unnamed:_24,unnamed:_25,unnamed:_26,unnamed:_27,unnamed:_28,unnamed:_29,unnamed:_30
0,Year,Month,United States dollar,Sterling pound,Euro,South Africa Rand,Uganda shilling\2,Tanzania shilling\2,Rwanda Franc,Burundi Franc,...,Danish kroner,Austrian schilling,Finn marka,Spanish peseta,Indian rupee,Hong kong dollar,Singapore dollar,Saudi riyal,Chinese Yuan,Australian dollar

In [ ]:
#Save clean files
gdp.to_csv(CLEAN_DATA / "gdp.csv", index=False)
monetary.to_csv(CLEAN_DATA / "monetary.csv", index=False)
trade_summary.to_csv(CLEAN_DATA / "trade_summary.csv", index=False)
inflation.to_csv(CLEAN_DATA / "inflation.csv", index=False)
principal_exports.to_csv(CLEAN_DATA / "principal_exports.csv", index=False)
value_exports_african.to_csv(CLEAN_DATA / "value_exports_african.csv", index=False)
value_exports_restofworld.to_csv(CLEAN_DATA / "value_exports_restofworld.csv", index=False)
exchange_rate.to_csv(CLEAN_DATA / "exchange_rate.csv", index=False)